<div class="grid_8">
    <!-- Start Loop -->
    <article class="post">
        <div class="grid_4 alpha">
            <div class="posthumb">
                <img src="images/assets/rel.jpg" alt="image"/>
            </div>
        </div>
        <div class="grid_8 ">
            <ul class="inline-list">
                <li><a href="#"><i class="icon-bookmark-empty"></i> How To's</a></li>
                <li><a href="#"><i class="icon-calendar-empty"></i> November 21, 2013</a></li>
                <li><a href="#"><i class="icon-comments"></i> 657</a></li>
            </ul>
            <div class="clearfix"></div>

            <h2 class="title-entry"><a href="#">DONEC SODALES SAGITTIS MAGNA</a></h2>
            <div class="content-entry">
                <p>Donec vivamus. Vel donec et scelerisque vestibulum. Condimentum aliquam, mollit magna velit nec, tempor cursus vitae sit aliquet neque purus. Ultrices lacus proin conubia dictum tempus, tempor pede vitae faucibus, sem auctor, molestie diam dictum aliquam. Dolor leo, ridiculus est ut cubilia nec</p>
            </div>
        </div>
        <div class="clearfix"></div>
        <hr/>
    </article>
    <article class="post">
        <div class="grid_4 alpha">
            <div class="posthumb">
                <img src="images/assets/rel.jpg" alt="image"/>
            </div>
        </div>
        <div class="grid_8 ">
            <ul class="inline-list">
                <li><a href="#"><i class="icon-bookmark-empty"></i> How To's</a></li>
                <li><a href="#"><i class="icon-calendar-empty"></i> November 21, 2013</a></li>
                <li><a href="#"><i class="icon-comments"></i> 657</a></li>
            </ul>
            <div class="clearfix"></div>

            <h2 class="title-entry"><a href="#">DONEC SODALES SAGITTIS MAGNA</a></h2>
            <div class="content-entry">
                <p>Donec vivamus. Vel donec et scelerisque vestibulum. Condimentum aliquam, mollit magna velit nec, tempor cursus vitae sit aliquet neque purus. Ultrices lacus proin conubia dictum tempus, tempor pede vitae faucibus, sem auctor, molestie diam dictum aliquam. Dolor leo, ridiculus est ut cubilia nec</p>
            </div>
        </div>
        <div class="clearfix"></div>
        <hr/>
    </article>
    <article class="post">
        <div class="grid_4 alpha">
            <div class="posthumb">
                <img src="images/assets/rel.jpg" alt="image"/>
            </div>
        </div>
        <div class="grid_8 ">
            <ul class="inline-list">
                <li><a href="#"><i class="icon-bookmark-empty"></i> How To's</a></li>
                <li><a href="#"><i class="icon-calendar-empty"></i> November 21, 2013</a></li>
                <li><a href="#"><i class="icon-comments"></i> 657</a></li>
            </ul>
            <div class="clearfix"></div>

            <h2 class="title-entry"><a href="#">DONEC SODALES SAGITTIS MAGNA</a></h2>
            <div class="content-entry">
                <p>Donec vivamus. Vel donec et scelerisque vestibulum. Condimentum aliquam, mollit magna velit nec, tempor cursus vitae sit aliquet neque purus. Ultrices lacus proin conubia dictum tempus, tempor pede vitae faucibus, sem auctor, molestie diam dictum aliquam. Dolor leo, ridiculus est ut cubilia nec</p>
            </div>
        </div>
        <div class="clearfix"></div>
        <hr/>
    </article>
    <article class="post">
        <div class="grid_4 alpha">
            <div class="posthumb">
                <img src="images/assets/rel.jpg" alt="image"/>
            </div>
        </div>
        <div class="grid_8 ">
            <ul class="inline-list">
                <li><a href="#"><i class="icon-bookmark-empty"></i> How To's</a></li>
                <li><a href="#"><i class="icon-calendar-empty"></i> November 21, 2013</a></li>
                <li><a href="#"><i class="icon-comments"></i> 657</a></li>
            </ul>
            <div class="clearfix"></div>

            <h2 class="title-entry"><a href="#">DONEC SODALES SAGITTIS MAGNA</a></h2>
            <div class="content-entry">
                <p>Donec vivamus. Vel donec et scelerisque vestibulum. Condimentum aliquam, mollit magna velit nec, tempor cursus vitae sit aliquet neque purus. Ultrices lacus proin conubia dictum tempus, tempor pede vitae faucibus, sem auctor, molestie diam dictum aliquam. Dolor leo, ridiculus est ut cubilia nec</p>
            </div>
        </div>
        <div class="clearfix"></div>
        <hr/>
    </article>

    <!-- END LOOP -->
    <div class="clearfix"></div>

    <!-- Pagination -->
    <ul class="pagination">
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">...</a></li>
        <li><a href="#">&rsaquo;</a></li>
        <li><a href="#">&raquo;</a></li>
    </ul>
    <!-- END BLOG, YEAH -->

</div>