<div class="grid_8" data-ng-controller="IndexController">
    <!-- LOOP HERE... PUT THE QUERY HERE -->
    <article class="singlepost page">
        <header>
            <h1 class="page-title">{{lastPost.title}}</h1>
        </header>

        <div class="clearfix"></div>
        <div class="devide"></div>
        <div class="content-entry" ng-bind-html="lastPost.content">

        </div>
        <div class="clearfix"></div>

    </article>
    <!-- END/CLOSE THE QUERY HERE -->
    <div class="clearfix"></div>
</div>