<!doctype html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/favicons/apple-touch-icon-144x144-precomposed.png">
    <!-- For iPhone with high-resolution Retina display: -->
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/favicons/apple-touch-icon-114x114-precomposed.png">
    <!-- For first- and second-generation iPad: -->
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/favicons/apple-touch-icon-72x72-precomposed.png">
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <link rel="apple-touch-icon-precomposed" href="/images/favicons/apple-touch-icon-precomposed.png">
    <link rel="icon" href="/images/favicons/favicon.ico" type="image/x-icon" />
    <title>Developer Blog</title>
    <meta name="description" content="some description" />
    <meta name="keywords" content="HTML,CSS,AngularJS,JavaScript,SailsJS,Phalcon,PHP," />
    <meta name="author" content="Ali Sadeghipour Körabbaslu" />
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <link rel="stylesheet" href="/css/font-awesome.min.css"/>
    <!--[if IE 7]>
    <link rel="stylesheet" href="/css/font-awesome-ie7.min.css">
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="/style.css" />
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Oswald:400,700,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/css/blogStyles.css">
    <script type="text/javascript" src="/js/jquery-2.0.3.min.js"></script>


</head>
<body>


<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>
<div id="status">
</div>

<div data-ng-controller="LayoutController" ng-cloak>
<!-- ooooooooooooooooooooooooooooooooooooooooooooo
IKLAN
oooooooooooooooooooooooooooooooooooooooooooooooo-->
<div class="iklon">
    <div id="sidr">
        <h2>Pages</h2>
        <ul>
            <li><a href="#">Home</a>
                <ul>
                    <li><a href="/menu/me">About Me</a></li>
                    <li><a href="/menu/diary">My Diary</a></li>
                    <li><a href="/menu/veganizm">Veganizm</a></li>
                    <li><a href="/menu/contact">Contact</a></li>
                </ul>
            </li>
            <li><a href="#">Single</a>
                <ul>
                    <li  data-ng-repeat="item in hotCat track by item.id"><a data-ng-href="/posts/{{item.title}}">{{item.title}}</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<div class="parentcontainer">
    <div id="mobile-header">
        <div id="container_12">
            <div class="grid_4">
                <a id="simple-menu" href="#sidr" class="sidrmenu"><i class="icon-list-ul"></i></a>
            </div>
            <div class="grid_4 text-center">
                <p>Britanews</p>
            </div>
            <div class="grid_4 text-right">
                <a id="righttrigger" href="#rightmenu" class="sidrmenu"><i class="icon-search"></i></a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div id="rightmenu">
        <h1>Search</h1>
        <form>
            <input type="text" placeholder="Search...">
        </form>
    </div>

    <!-- oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
        HEADER
    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo -->
    <header id="mainheader" class="mobile-hide">
        <div class="container container_12">
            <!-- Logo -->
            <div class="grid_3 logo">
                <a href="#"><img src="images/logo.png" class="mobile-hide" alt="britanews"/></a>
            </div>
            <div class="grid_9 text-right">
                <form class="headersearch" name="some_name" action="{form action link}" method="post">
                    <input type="text" name="search" class="srcfield" onfocus="if(this.value=='Search'){this.value=''};" onblur="if(this.value==''){this.value='Search'};" value="Search"/>
                    <div class="hdrbtn scnclr" id="search"><i class="icon-search"></i></div>
                    <div class="clearfix"></div>
                </form>
                <div class="topmenu">
                    <div class="hdrbtn scnclr"><i class="icon-globe"></i>
                        <ul class="fadeout">
                            <li><a href="#"><i class="icon-facebook"></i> Facebook</a></li>
                            <li><a href="#"><i class="icon-linkedin"></i> Twitter</a></li>
                            <li><a href="#"><i class="icon-instagram"></i> Instagram</a></li>
                        </ul>
                    </div>
                    <div class="hdrbtn scnclr"><i class="icon-th-list"></i>
                        <ul class="fadeout">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Pages</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Post</a></li>
                            <li><a href="#">Shortcodes</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <!-- Menu -->
        <div class="container container_12">
            <div class="grid_12">
                <nav>
                    <div>
                        <ul class="mainmenu">
                            <li><a href="#" class="icon-home active"></a>
                                <ul>
                                    <li><a href="/menu/me">About Me</a></li>
                                    <li><a href="/menu/diary">My Diary</a></li>
                                    <li><a href="/menu/veganizm">Veganizm</a></li>
                                    <li><a href="/menu/contact">Contact</a></li>
                                </ul>
                            </li>
                            <li><a href="#" class=""><i class="icon-list-ul"></i></a>
                                <ul>
                                    <li  data-ng-repeat="item in hotCat track by item.id"><a data-ng-href="/posts/{{item.title}}">{{item.title}}</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="clearfix"></div>
    </header>
    <div class="clearfix"></div>

    <div class="clearfix"></div>

    <!-- oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
        Content/Teaser
    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo -->
    <section id="maincontent">
        <!-- BREADCRUMBS -->
        <div class="container_12">
            <div class="grid_6">
                <ul class="breadcrumbs inline-list">
<!--                    <li><a href="#">Home</a></li>-->
<!--                    <li>Lastest Post</li>-->
                </ul>
            </div>
            <div class="grid_6 text-right">
                <div id="Date" class="mobile-hide"></div>
            </div>
            <div class="clearfix"></div>
        </div>

        <!-- CONTENT/ARTIKEL -->
        <div class="container_12">

           <!-- TODO: PUT CONTENT IN HERE-->

            <?php
            echo $this->getContent();
            ?>

            <!-- Start Sidebar -->
            <div  class="grid_4">
                <div class="widgetbox blue news">
                    <h4>Latest Technology News</h4>
                    <li  data-ng-show="lastNews.length==0">Loding...</li>
                    <ul data-ng-repeat="item in lastNews">
                       <li> <a target="_blank" data-ng-href="{{item.link}}">{{item.title}}</a></li>
                    </ul>
                </div>
                <div class="widgetbox darkblue">
                    <h4><i class="icon-comments"></i> Recent Comments</h4>
                    <article class="comitem" data-ng-repeat="item in comments">
                        <div class="grid_3">
                            <div class="comthumb"><img data-ng-src="{{item.avatar}}" class="circle" alt="image"/></div>
                        </div>
                        <div class="grid_9">
                            <strong>{{item.email}}</strong> <em>{{item.body}}</em>
                        </div>
                    </article>
                </div>

                <div class="widgetbox grey">
                    <h4><i class="icon-bookmark"></i> Hot Categories</h4>
                    <ul class="categorylist">
                        <li data-ng-repeat="item in hotCat track by item.id">
                            <a data-ng-href="category/getCategory/{{item.title}}">{{item.title}}</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"></div>
            <!-- END sidebar -->
        </div>
        <div class="clearfix"></div>
    </section>
    <div class="clearfix"></div>
    <!-- oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
        Footer
    oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo -->
    <footer id="mainfooter">
        <div class="container footer container_12 threecolumns">
            <div class="fooline"></div> <!-- Extra line for footer -->
            <div class="grid_4">
                <div class="foowid">
                    <h3 class="fword fwidtit">FEATURED POSTS</h3>
                    <div class="featuredslides">
                        <ul class="slides">
                            <li data-ng-repeat="item in featured">
                                <img data-ng-src="{{item.image}}" alt="image"/>
                                <div class="capcontain">
                                    <div class="slidetitle">
                                        <div class="slidedate">{{item.modified_date}}</div>
                                        <div class="clear"></div>
                                        <h2>{{item.title}}</h2>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="foowid">
                    <h3 class="fword fwidtit">ABOUT THIS BLOG</h3>
                    <img src="images/assets/iconlogo.jpg" alt="image" class="pushright"/>
                    <p>In this blog I will try to write my experiences on software developing.</p>
                    <ul class="contact-list">
                        <li><i class="icon-envelope"></i> ali.korabbaslu@gmail.com</li>
                    </ul>
                </div>
            </div>
            <div class="grid_4">
                <div class="foowid">
                    <h3 class="fword fwidtit">RECENT POSTS</h3>
                    <article class="recposts" data-ng-repeat="item in recentPosts">
                        <div class="grid_6 text-right">
                            <div class="posthumb">
                                <a href="posts/{{item.title}}"><img data-ng-src="{{item.image}}" alt="image"/></a>
                            </div>
                        </div>
                        <div class="grid_6">
                            <small>{{item.create_date}}</small>
                            <h2><a href="#">{{item.description}}</a></h2>
                        </div>
                    </article>
                    <div class="clearfix"></div>
                </div>

                <!-- Video Of The Week -->
                <div class="foowid">
                    <h3 class="fword fwidtit">VIDEO OF THE WEEK</h3>
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/_moMI9nzbMU" frameborder="0" allowfullscreen></iframe>
                    <div class="clearfix"></div>
                </div>


            </div>
            <div class="grid_4 omega">
                <!-- FLICKR -->
                <div class="foowid">
                    <h3 class="fword fwidtit">FLICKR FEEDS</h3>
                    <ul>
                        <div id="flickr" class="flickr"></div>
                    </ul>
                    <div class="clearfix"></div>
                </div>

                <!-- Review -->
                <div class="foowid">
                    <h3 class="fword fwidtit">LATEST REVIEW</h3>
                    <article class="recposts">
                        <div class="grid_3">
                            <div class="posthumb">
                                <img src="http://placehold.it/67x67" alt="image"/>
                            </div>
                        </div>
                        <div class="grid_9">
                            <h2><a href="#">New Macbook Pro Review Lorem Ipsu.</a></h2>
                            <small>November 16, 2013</small>
                            <div class="clearfix"></div>
                            <div class="rating">
                                <i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i>
                            </div>

                        </div>
                    </article>
                    <article class="recposts">
                        <div class="grid_3">
                            <div class="posthumb">
                                <img src="http://placehold.it/67x67" alt="image"/>
                            </div>
                        </div>
                        <div class="grid_9">
                            <h2><a href="#">The One2Touch Softpad S1 NFC keyboard review</a></h2>
                            <small>November 16, 2013</small>
                            <div class="clearfix"></div>
                            <div class="rating">
                                <i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i>
                            </div>

                        </div>
                    </article>
                    <article class="recposts">
                        <div class="grid_3">
                            <div class="posthumb">
                                <img src="http://placehold.it/67x67" alt="image"/>
                            </div>
                        </div>
                        <div class="grid_9">
                            <h2><a href="#">HTC One Max review</a></h2>
                            <small>November 16, 2013</small>
                            <div class="clearfix"></div>
                            <div class="rating">
                                <i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class=" icon-star-empty"></i>
                            </div>

                        </div>
                    </article>
                    <article class="recposts">
                        <div class="grid_3">
                            <div class="posthumb">
                                <img src="http://placehold.it/67x67" alt="image"/>
                            </div>
                        </div>
                        <div class="grid_9">
                            <h2><a href="#">The MiniSuit Keyboard stand case for Nexus 7 (2013)</a></h2>
                            <small>November 16, 2013</small>
                            <div class="clearfix"></div>
                            <div class="rating">
                                <i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-half-empty"></i><i class="icon-star-empty"></i>
                            </div>

                        </div>
                    </article>

                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>

        <!-- ooooooooooooooo
        COPYRIGHT
        ooooooooooooooooooo-->

        <div class="clearfix"></div>
    </footer>
    <!-- END #mainfooter FOOTER -->
    <div class="clearfix"></div>
</div> <!-- end .parentcontainer -->
<a href="#" class="scrollup"><i class="icon-chevron-up"></i></a>


<script type="text/javascript" src="/js/plugin.js"></script>
<script type="text/javascript" src="/js/custom.js"></script>
<script type="text/javascript" src="/js/vendor/plusone.js"></script>

<script src="/js/vendor/angular.min.js"></script>
<script src="/js/vendor/angular-resource.min.js"></script>
<script src="/js/vendor/angular-sanitize.min.js"></script>
<script src="/js/vendor/angular-route.min.js"></script>
<script src="/js/vendor/angular-animate.min.js"></script>
<script data-main="/js/gaboot" src="/src/require.js"></script>
<script src="/js/vendor/fb.js"></script>

</div>
</body>
</html>
